/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { WCRO } from "./WCRO";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { WCRO__factory } from "./factories/WCRO__factory";
